#!/usr/bin/env python3
from pathlib import Path
from textwrap import dedent


ROOT = Path(__file__).parent
BLOG_DIR = ROOT / "blog"


def related_block(items):
    links = "\n".join(
        f'        <li><a href="{href}">{label}</a></li>' for href, label in items
    )
    return dedent(
        f"""
        <h2>Related Reading</h2>
        <ul>
{links}
        </ul>"""
    ).strip()


TOP_PAGES = {
    "ai-brand-photography-cost.html": {
        "replacements": [
            (
                '<p class="article-subtitle">The real numbers nobody publishes. A line-item comparison of traditional photoshoots vs AI brand systems, from $500 starter kits to $20K enterprise productions.</p>',
                '<p class="article-subtitle">AI brand photography usually costs about $500 to $5,000 for a reusable content system, while traditional brand shoots often land between $5,000 and $25,000+ per production. This guide breaks down the real cost ranges, tradeoffs, and when each option makes sense.</p>',
            ),
            (
                '"text": "I create done-for-you contents typically range from $500 to $5,000 depending on scope. A basic prompt library and 50+ images starts around $500-1,000 DIY. A done-for-you system with brand DNA, photography, content calendar, and automation runs $5,000-$10,000 \\u2014 still 60-80% less than traditional photoshoots at equivalent volume."',
                '"text": "AI brand photography systems typically range from $500 to $5,000 depending on scope. A basic prompt library and 50+ images starts around $500-$1,000 DIY. A done-for-you system with brand DNA, photography, content calendar, and automation runs $5,000-$10,000, still 60-80% less than traditional photoshoots at equivalent volume."',
            ),
            (
                '"name": "How long does it take to build an I create done-for-you content?"',
                '"name": "How long does it take to build an AI brand photography system?"',
            ),
            (
                "The Traditional Photoshoot: What It Actually Costs",
                "What does a traditional brand photoshoot actually cost?",
            ),
            (
                "The Hidden Costs Nobody Mentions",
                "What hidden costs make traditional photography more expensive?",
            ),
            (
                "AI Brand Photography: The Real Cost Structure",
                "How much does AI brand photography cost in practice?",
            ),
            (
                "The Comparison Table",
                "How do AI brand photography and traditional shoots compare side by side?",
            ),
            (
                "Where the 80% Savings Actually Come From",
                "Where do the 60-80% savings actually come from?",
            ),
            (
                "When Traditional Photography Still Makes Sense",
                "When does traditional photography still make sense?",
            ),
            (
                "The Real Question Isn't Cost. It's Output.",
                "What are you actually buying: lower cost or more content output?",
            ),
            (
                "What to Look for in an AI Brand Photography System",
                "What should you look for in an AI brand photography system?",
            ),
            (
                "Bottom Line: The Numbers",
                "What is the bottom line on AI brand photography pricing?",
            ),
        ],
    },
    "ai-photography-prompts-that-dont-look-ai.html": {
        "replacements": [
            (
                '<p class="article-subtitle">Real prompts with real camera specs. Each one is designed to produce images that look like they were shot on film by a skilled photographer, not generated by a machine. Bookmark this page.</p>',
                '<p class="article-subtitle">The best AI photography prompts use camera realism, imperfect details, and scene-specific direction instead of generic "ultra-realistic" language. These 50 prompts are organized by use case and designed to generate images that look shot, not generated.</p>',
            ),
            (
                "The Anti-AI Philosophy",
                "What makes an AI photography prompt look real instead of fake?",
            ),
            (
                "Food Photography (Prompts 1-10)",
                "What AI prompts work for realistic food photography?",
            ),
            (
                "Fashion &amp; Apparel (Prompts 11-20)",
                "What AI prompts work for fashion and apparel photography?",
            ),
            (
                "Hotel &amp; Real Estate (Prompts 21-30)",
                "What AI prompts work for hotel and real estate imagery?",
            ),
            (
                "Product Photography (Prompts 31-40)",
                "What AI prompts work for product photography?",
            ),
            (
                "Portrait &amp; Lifestyle (Prompts 41-50)",
                "What AI prompts work for portraits and lifestyle imagery?",
            ),
            (
                "How to Use These Prompts",
                "How should you use these prompts without getting generic results?",
            ),
            (
                "The Framework, Summarized",
                "What is the prompt framework in one view?",
            ),
        ],
    },
    "ai-vs-traditional-product-photography.html": {
        "replacements": [
            (
                '<p class="article-subtitle">An honest comparison. Not a pitch for one side. Both approaches have clear strengths and real limitations. Here\'s how to decide.</p>',
                '<p class="article-subtitle">AI product photography wins on speed, scale, and content volume, while traditional photography still wins when exact product accuracy and hero-level realism matter most. This guide shows where each approach fits and how to combine them.</p>',
            ),
            (
                "Where AI Photography Wins",
                "Where does AI product photography beat traditional photography?",
            ),
            (
                "Where Traditional Photography Wins",
                "Where does traditional product photography still win?",
            ),
            (
                "The Scorecard",
                "How do AI and traditional product photography compare side by side?",
            ),
            (
                "The Decision Framework",
                "How should you decide between AI and traditional product photography?",
            ),
            (
                "The Hybrid Approach (What Smart Brands Are Doing)",
                "What does a hybrid product photography workflow look like?",
            ),
            (
                "What This Means for Your Budget",
                "What does this mean for your budget?",
            ),
            (
                "The Bottom Line",
                "What is the bottom line for most brands?",
            ),
        ],
    },
    "ai-brand-photography-vs-stock-photos.html": {
        "replacements": [
            (
                '<p class="article-subtitle">That photo of a smiling person shaking hands in a glass office? Your competitor is using the same one. So are 200 other businesses. Here is why stock photos are silently undermining your brand and what to use instead.</p>',
                '<p class="article-subtitle">Stock photos are cheap and easy, but they weaken trust, recognition, and brand distinctiveness because the same visuals show up everywhere. AI brand photography gives you custom visuals at a lower cost than a traditional shoot and with more control than stock.</p>',
            ),
            (
                "The Stock Photo Problem Is Worse Than You Think",
                "Why are stock photos worse than most brands think?",
            ),
            (
                "What AI Brand Photography Actually Is",
                "What is AI brand photography?",
            ),
            (
                "Side-by-Side Comparison",
                "How do stock photos and AI brand photography compare side by side?",
            ),
            (
                'The Real Cost of "Free" Stock Photos',
                "What is the real cost of free stock photos?",
            ),
            (
                "Where AI Brand Photography Wins by the Widest Margin",
                "Where does AI brand photography win by the widest margin?",
            ),
            (
                "The Objections (Addressed Honestly)",
                "What are the honest objections to AI brand photography?",
            ),
            (
                "How to Make the Switch",
                "How should you switch from stock photos to AI brand photography?",
            ),
            (
                "The Bottom Line",
                "What is the bottom line on stock photos versus AI brand photography?",
            ),
        ],
        "related": related_block(
            [
                ("/blog/ai-brand-photography-cost.html", "How Much Does AI Brand Photography Actually Cost?"),
                ("/blog/build-brand-identity-with-ai.html", "How to Build a Complete Brand Identity Using AI in 7 Days"),
                ("/blog/ai-photography-prompts-that-dont-look-ai.html", "50 AI Photography Prompts That Don't Look Like AI"),
                ("/blog/hiring-photographer-vs-ai-photography.html", "Hiring a Photographer vs AI Photography"),
            ]
        ),
    },
    "build-brand-identity-with-ai.html": {
        "replacements": [
            (
                "<p>Two years ago, building a brand identity from scratch took 4 to 12 weeks and cost $5,000 to $50,000. You needed a brand strategist, a graphic designer, a photographer, a copywriter, and someone to stitch it all together into a cohesive system. The process was slow, expensive, and often produced work that looked like every other brand in the category because the same agencies were running the same playbooks.</p>",
                "<p>You can build a usable brand identity with AI in seven days if you treat it like a system: define brand DNA, generate photography direction, build the content structure, and automate the publishing layer. This guide walks through that sequence and where human judgment still matters.</p>",
            ),
            (
                "Day 1-2: Define Your Brand DNA",
                "How do you define your brand DNA in days 1-2?",
            ),
            (
                "Day 3-4: Generate Your Brand Photography",
                "How do you generate brand photography in days 3-4?",
            ),
            (
                "Day 5: Build Your Content Calendar",
                "How do you build your content calendar on day 5?",
            ),
            (
                "Day 6: Set Up Automation",
                "How do you set up automation on day 6?",
            ),
            (
                "Day 7: Launch",
                "How do you launch the system on day 7?",
            ),
            (
                "The Framework in Practice: What Five Brands Look Like",
                "What does this framework look like across five brands?",
            ),
            (
                "The Honest Assessment",
                "What is the honest assessment of building a brand identity with AI?",
            ),
        ],
    },
    "content-calendar-template-small-business.html": {
        "replacements": [
            (
                '<p class="article-subtitle">A complete 30-day content calendar with daily themes, caption frameworks, hashtag strategy, and posting times. Built for small businesses that want consistency without hiring a marketing team.</p>',
                '<p class="article-subtitle">A small business content calendar works best when it assigns repeatable daily themes, clear caption frameworks, and a realistic posting rhythm. This guide gives you the 30-day structure, batching workflow, and ratios that make consistency possible.</p>',
            ),
            (
                "The Daily Theme System",
                "What is the daily theme system for a small business content calendar?",
            ),
            (
                "Caption Frameworks by Day",
                "What caption frameworks work for each day of the week?",
            ),
            (
                "The 30-Day Template",
                "What does a 30-day small business content calendar look like?",
            ),
            (
                "Hashtag Strategy That Actually Works",
                "What hashtag strategy actually works in 2026?",
            ),
            (
                "Best Posting Times in 2026",
                "When should a small business post in 2026?",
            ),
            (
                "Tools to Manage Your Content Calendar",
                "What tools help manage a content calendar?",
            ),
            (
                "Content Batching: How to Create a Month of Content in One Sitting",
                "How do you batch a month of content in one sitting?",
            ),
            (
                "The Content Mix: Ratios That Work",
                "What content mix ratios actually work?",
            ),
            (
                "What to Do When You Run Out of Ideas",
                "What should you do when you run out of content ideas?",
            ),
            (
                "Common Mistakes That Kill Content Calendars",
                "What mistakes kill small business content calendars?",
            ),
            (
                "Download the Full Template",
                "Where can you get the full template?",
            ),
            (
                '<p><strong>No visual consistency.</strong> If every post looks different — different fonts, colors, photo styles — your feed looks chaotic. Pick a visual identity and stick to it. <a href="/blog/build-brand-identity-with-ai.html">I create done-for-you contents</a> make this easy because every image is generated within the same visual parameters.</p>',
                '<p><strong>No visual consistency.</strong> If every post looks different — different fonts, colors, photo styles — your feed looks chaotic. Pick a visual identity and stick to it. <a href="/blog/build-brand-identity-with-ai.html">AI brand photography systems</a> make this easier because every image is generated within the same visual parameters.</p>',
            ),
        ],
        "related": related_block(
            [
                ("/blog/social-media-content-strategy-small-business.html", "Social Media Content Strategy for Small Business"),
                ("/blog/how-to-batch-content-creation.html", "How to Batch Content Creation"),
                ("/blog/how-to-write-instagram-captions.html", "How to Write Instagram Captions That Actually Convert"),
                ("/blog/ai-content-automation-small-business.html", "AI Content Automation for Small Business"),
            ]
        ),
    },
    "ecommerce-ai-product-photos.html": {
        "replacements": [
            (
                "<p>Every DTC brand hits the same wall. You have a product you believe in, a Shopify store that looks decent, and a marketing strategy that requires a constant stream of fresh visual content. Then you get the quote from a product photographer: $200 to $500 per SKU for clean white-background shots. $1,000 to $3,000 per day for lifestyle photography. $5,000 to $20,000 for a full campaign shoot with models, locations, and styling.</p>",
                "<p>AI product photography can cut ecommerce photo costs by 70-80% for lifestyle, campaign, and social content, but it still needs guardrails around product accuracy. This guide covers the cost math, the workflow, and where hybrid setups outperform either option alone.</p>",
            ),
            (
                "The Real Cost of Traditional Product Photography",
                "What does traditional product photography really cost for ecommerce brands?",
            ),
            (
                "What AI Product Photography Costs in 2026",
                "What does AI product photography cost in 2026?",
            ),
            (
                "The AI Product Photography Workflow",
                "How does the AI product photography workflow work?",
            ),
            (
                "Where AI Product Photography Excels",
                "Where does AI product photography perform best?",
            ),
            (
                "Where AI Product Photography Falls Short",
                "Where does AI product photography fall short?",
            ),
            (
                "The Hybrid Model: What Smart Brands Actually Do",
                "What does a hybrid ecommerce photography model look like?",
            ),
            (
                "Getting Started Without Breaking Anything",
                "How should you start using AI product photography without breaking your catalog?",
            ),
            (
                '<p>We build custom I create done-for-you contents for e-commerce brands. Visual DNA, prompt libraries, automated content pipelines. Your product looking its best, everywhere, without the studio bill.</p>',
                '<p>We build custom AI product photography systems for e-commerce brands. Visual DNA, prompt libraries, and automated content pipelines that keep your products looking their best without the studio bill.</p>',
            ),
        ],
    },
    "how-to-automate-instagram-posting.html": {
        "replacements": [
            (
                '<p class="article-subtitle">The exact pipeline I use to post consistent Instagram content for multiple brands without touching my phone. Content queue, scheduling engine, auto-posting API — all of it.</p>',
                '<p class="article-subtitle">Instagram posting automation works when you separate three layers: a content queue, a scheduling engine, and an approved posting API. This guide shows the actual stack, the setup steps, and the mistakes that break reliability.</p>',
            ),
            (
                'Why Most "Automation" Solutions Fall Short',
                "Why do most Instagram automation solutions fall short?",
            ),
            (
                "The Architecture: Three Layers",
                "What does a real Instagram automation stack look like?",
            ),
            (
                "Setting It Up: The Practical Steps",
                "How do you set up Instagram posting automation step by step?",
            ),
            (
                "The Time Math",
                "How much time does Instagram automation actually save?",
            ),
            (
                "Scaling Beyond Single Account",
                "How do you scale automation beyond one account?",
            ),
            (
                "Common Mistakes to Avoid",
                "What mistakes break Instagram automation?",
            ),
            (
                "The Bottom Line",
                "What is the bottom line on Instagram posting automation?",
            ),
        ],
        "related": related_block(
            [
                ("/blog/ai-content-automation-small-business.html", "AI Content Automation for Small Business"),
                ("/blog/n8n-vs-zapier-vs-make-automation.html", "n8n vs Zapier vs Make"),
                ("/blog/how-to-batch-content-creation.html", "How to Batch Content Creation"),
                ("/blog/social-media-content-strategy-small-business.html", "Social Media Content Strategy for Small Business"),
            ]
        ),
    },
    "hiring-photographer-vs-ai-photography.html": {
        "replacements": [
            (
                '<p class="article-subtitle">The actual numbers, the quality tradeoffs, and the hybrid approach that most smart brands are quietly adopting in 2026.</p>',
                '<p class="article-subtitle">Hiring a photographer still wins for exact human likeness, product precision, and high-stakes brand assets, while AI photography wins for speed, volume, and repeatable content production. This guide compares both on cost, quality, turnaround, and scale.</p>',
            ),
            (
                "<p>I've been on both sides of this. I've hired photographers for brand shoots. I've been the person coordinating the studio, the models, the shot list. And I've built I create done-for-you contents that replaced most of that process for a fraction of the cost.</p>",
                "<p>I've been on both sides of this. I've hired photographers for brand shoots. I've been the person coordinating the studio, the models, the shot list. And I've built AI brand photography systems that replaced most of that process for a fraction of the cost.</p>",
            ),
            (
                "<p>An I create done-for-you content produces images in hours. Not days. Hours. I've built brand content libraries — 100+ curated, on-brand images — in a single afternoon. The speed advantage compounds when you need to refresh content quarterly or react to a new campaign quickly.</p>",
                "<p>An AI brand photography system produces images in hours, not days. I've built brand content libraries — 100+ curated, on-brand images — in a single afternoon. The speed advantage compounds when you need to refresh content quarterly or react to a new campaign quickly.</p>",
            ),
            (
                "The Cost Comparison: Real Numbers",
                "How much does a photographer cost versus AI photography?",
            ),
            (
                "Quality Comparison by Category",
                "How does quality compare across use cases?",
            ),
            (
                "Turnaround Time: Not Even Close",
                "How much faster is AI photography than a photographer?",
            ),
            (
                "Consistency and Scalability",
                "How do consistency and scalability compare?",
            ),
            (
                "Creative Control and the Revision Process",
                "How much creative control do you get with each option?",
            ),
            (
                "When You Absolutely Need a Real Photographer",
                "When do you absolutely need a real photographer?",
            ),
            (
                "When AI Wins Without Question",
                "When does AI win without question?",
            ),
            (
                "The Hybrid Approach That Actually Works",
                "What does the smartest hybrid approach look like?",
            ),
            (
                "The Verdict",
                "What is the verdict for most brands?",
            ),
        ],
        "related": related_block(
            [
                ("/blog/ai-brand-photography-cost.html", "How Much Does AI Brand Photography Actually Cost?"),
                ("/blog/ai-vs-traditional-product-photography.html", "AI vs Traditional Product Photography"),
                ("/blog/restaurant-ai-photography.html", "AI Photography for Restaurants"),
                ("/blog/ecommerce-ai-product-photos.html", "AI Product Photography for E-commerce"),
            ]
        ),
    },
    "how-to-create-brand-style-guide-ai.html": {
        "replacements": [
            (
                '<p class="article-subtitle">The brand style guide used to take 6 weeks and a $15K agency retainer. Now you can build one in a weekend that actually gets used — because AI does the heavy lifting on every component.</p>',
                '<p class="article-subtitle">A modern brand style guide should do more than document colors and fonts. It should define the rules that humans and AI tools both use to produce on-brand content consistently. This guide shows how to build that system step by step.</p>',
            ),
            (
                "What Goes in a Brand Style Guide (And What Doesn't)",
                "What should go in a brand style guide and what should stay out?",
            ),
            (
                "The Brand DNA Document: The Foundation",
                "Why does the Brand DNA document matter first?",
            ),
            (
                "Step 1: Define Your Color Palette with AI",
                "How do you define your color palette with AI?",
            ),
            (
                "Step 2: Lock Your Typography",
                "How do you lock your typography?",
            ),
            (
                "Step 3: Build Your Voice Guide",
                "How do you build a voice guide?",
            ),
            (
                "Step 4: Define Your Photography Direction",
                "How do you define your photography direction?",
            ),
            (
                'Step 5: Create Usage Rules and the "Never" List',
                'How do you create usage rules and a "never" list?',
            ),
            (
                "Step 6: Assemble and Distribute",
                "How do you assemble and distribute the guide?",
            ),
            (
                "Common Mistakes That Kill Brand Guides",
                "What mistakes kill brand guides?",
            ),
            (
                "The AI Advantage: Speed and Consistency",
                "What is the AI advantage in building a style guide?",
            ),
            (
                '<p>When you <a href="/blog/ai-brand-photography-cost.html">invest in an I create done-for-you content</a>, the photography direction section of your style guide becomes the prompt template library. Every image generation pulls from these rules automatically.</p>',
                '<p>When you <a href="/blog/ai-brand-photography-cost.html">invest in an AI brand photography system</a>, the photography direction section of your style guide becomes the prompt template library. Every image generation pulls from these rules automatically.</p>',
            ),
            (
                '<p>The bigger advantage is what comes after. When your brand rules exist in a structured, machine-readable format, every AI tool in your stack can enforce them automatically. Your <a href="/blog/ai-brand-photography-cost.html">I create done-for-you content</a> references the guide for every image. Your copywriting tool matches the voice. Your content automation pipeline stays on-brand without manual review of every post.</p>',
                '<p>The bigger advantage is what comes after. When your brand rules exist in a structured, machine-readable format, every AI tool in your stack can enforce them automatically. Your <a href="/blog/ai-brand-photography-cost.html">AI brand photography system</a> references the guide for every image. Your copywriting tool matches the voice. Your content automation pipeline stays on-brand without manual review of every post.</p>',
            ),
        ],
        "related": related_block(
            [
                ("/blog/build-brand-identity-with-ai.html", "How to Build a Complete Brand Identity Using AI in 7 Days"),
                ("/blog/ai-brand-photography-cost.html", "How Much Does AI Brand Photography Actually Cost?"),
                ("/blog/build-visual-brand-instagram.html", "How to Build a Visual Brand on Instagram"),
                ("/blog/ai-photography-prompts-that-dont-look-ai.html", "50 AI Photography Prompts That Don't Look Like AI"),
            ]
        ),
    },
    "ai-content-automation-small-business.html": {
        "replacements": [
            (
                '<p class="article-subtitle">How to build a content machine that generates, schedules, and posts brand content automatically. The same system we run for brands doing 60+ posts per month with zero daily manual work.</p>',
                '<p class="article-subtitle">Content automation for small businesses means turning content planning, copy generation, visual production, and publishing into one repeatable workflow. This guide shows the practical stack, tradeoffs, and realistic outcomes.</p>',
            ),
            (
                'What "Content Automation" Actually Means',
                "What does content automation actually mean for a small business?",
            ),
            (
                "Step 1: Build Your Content Calendar",
                "How do you build the content calendar?",
            ),
            (
                "Step 2: Generate Your Copy",
                "How do you generate the copy?",
            ),
            (
                "Step 3: Generate Your Visuals",
                "How do you generate the visuals?",
            ),
            (
                "Step 4: Set Up Auto-Posting",
                "How do you set up auto-posting?",
            ),
            (
                "Step 5: Monitor and Iterate",
                "How do you monitor and iterate?",
            ),
            (
                "The Full Pipeline: What It Looks Like in Practice",
                "What does the full content automation pipeline look like?",
            ),
            (
                "DIY vs Done-For-You: The Real Comparison",
                "Should you do content automation yourself or buy it done for you?",
            ),
            (
                "The Minimum Viable Stack",
                "What is the minimum viable stack?",
            ),
            (
                "The Full Stack (What We Build)",
                "What does the full stack look like?",
            ),
            (
                "What to Expect: Realistic Outcomes",
                "What results should you realistically expect?",
            ),
            (
                "Getting Started",
                "How should you get started?",
            ),
            (
                "<p>AI image generation solves this, but only if you have a system. Random prompt experimentation produces random results. A I create done-for-you content produces consistent, on-brand images every time.</p>",
                "<p>AI image generation solves this, but only if you have a system. Random prompt experimentation produces random results. An AI brand photography system produces consistent, on-brand images every time.</p>",
            ),
        ],
    },
    "ai-photography-for-personal-brands.html": {
        "replacements": [
            (
                '<p class="article-subtitle">Your personal brand needs a visual identity that goes beyond one headshot. AI photography gives coaches, consultants, and thought leaders a complete visual system without ever booking a photographer.</p>',
                '<p class="article-subtitle">AI photography helps personal brands build a full visual library for LinkedIn, websites, and sales collateral without relying on one outdated headshot or repeated studio shoots. This guide shows how to use it without making your brand look fake.</p>',
            ),
            (
                "What Personal Brand Photography Actually Needs",
                "What does personal brand photography actually need?",
            ),
            (
                'The "But People Will Know It Is AI" Objection',
                "Will people know your images are AI?",
            ),
            (
                "AI Photography for LinkedIn Specifically",
                "How should personal brands use AI photography on LinkedIn?",
            ),
            (
                "Case Study: 90-Day LinkedIn Authority Build",
                "What does a 90-day LinkedIn authority build look like?",
            ),
            (
                "Beyond LinkedIn: Website and Marketing Collateral",
                "How should you use the system beyond LinkedIn?",
            ),
            (
                "Building Your Personal Brand Visual System",
                "How do you build a personal brand visual system?",
            ),
            (
                "What This Actually Costs",
                "What does AI personal brand photography cost?",
            ),
            (
                "The Competitive Advantage Is Temporary",
                "Why is the competitive advantage temporary?",
            ),
        ],
        "related": related_block(
            [
                ("/blog/linkedin-personal-brand-guide.html", "LinkedIn Personal Brand Guide"),
                ("/blog/personal-brand-content-plan.html", "Personal Brand Content Plan"),
                ("/blog/ai-headshots-for-business.html", "AI Headshots for Business"),
                ("/blog/how-to-create-brand-style-guide-ai.html", "How to Create a Brand Style Guide with AI"),
            ]
        ),
    },
    "ai-product-photography-amazon-sellers.html": {
        "replacements": [
            (
                '<p class="article-subtitle">Amazon has specific image requirements that determine whether your listing converts or dies. Here\'s exactly where AI works, where it doesn\'t, and the cost math for sellers launching 50+ products.</p>',
                '<p class="article-subtitle">AI product photography can support Amazon launches in secondary images, A+ content, and scalable creative production, but it still cannot replace compliant main images. This guide shows exactly where AI fits and where real photography is still required.</p>',
            ),
            (
                "Amazon's Image Requirements: The Non-Negotiables",
                "What image rules does Amazon actually enforce?",
            ),
            (
                "Main Image: AI Cannot Do This (Yet)",
                "Why can't AI handle the main Amazon image yet?",
            ),
            (
                "Lifestyle Images (Slots 2-4): Where AI Shines",
                "Where does AI shine in Amazon lifestyle images?",
            ),
            (
                "Infographic Images (Slots 5-6): AI Assists, Design Finishes",
                "How does AI help with Amazon infographic images?",
            ),
            (
                "A+ Content: AI's High-Impact Zone",
                "Where is AI most useful in Amazon A+ Content?",
            ),
            (
                "Cost Per SKU: The Real Comparison",
                "What is the real cost per SKU?",
            ),
            (
                "The 50+ Product Launch Workflow",
                "What does a 50+ product launch workflow look like?",
            ),
            (
                "Limitations and Risks",
                "What limitations and risks should Amazon sellers watch?",
            ),
            (
                "The Bottom Line for Amazon Sellers",
                "What is the bottom line for Amazon sellers?",
            ),
        ],
        "related": related_block(
            [
                ("/blog/ai-vs-traditional-product-photography.html", "AI vs Traditional Product Photography"),
                ("/blog/ecommerce-ai-product-photos.html", "AI Product Photography for E-commerce"),
                ("/blog/amazon-listing-optimization-guide.html", "Amazon Listing Optimization Guide"),
                ("/blog/shopify-store-photography-guide.html", "Shopify Store Photography Guide"),
            ]
        ),
    },
    "restaurant-ai-photography.html": {
        "replacements": [
            (
                "<p>Most restaurants post to Instagram the same way: someone on staff grabs their phone between tickets, snaps a picture of a plate under fluorescent lighting, slaps a filter on it, and hits publish. The result is a feed that looks like it was curated by someone who has never eaten at the restaurant. You know the look. Blown-out whites, muddy shadows, zero consistency.</p>",
                "<p>Restaurant AI photography is most useful when you need consistent lifestyle content, menu atmosphere, and social volume without booking new shoots every quarter. This guide covers the prompts, workflows, limits, and where real photography still matters.</p>",
            ),
            (
                "Why Restaurant Photography Is Broken",
                "Why is restaurant photography broken for most restaurants?",
            ),
            (
                "What AI Restaurant Photography Actually Looks Like in 2026",
                "What does restaurant AI photography actually look like in 2026?",
            ),
            (
                "Prompt Formulas That Actually Work",
                "What prompt formulas actually work for restaurant AI photography?",
            ),
            (
                "Building a Content Calendar Around AI Photography",
                "How do you build a restaurant content calendar around AI photography?",
            ),
            (
                "The Case Study: A Smash Burger Brand Built Entirely on AI",
                "What does the smash burger case study show?",
            ),
            (
                "Common Mistakes to Avoid",
                "What mistakes ruin AI restaurant photography?",
            ),
            (
                "When You Still Need a Real Photographer",
                "When do restaurants still need a real photographer?",
            ),
            (
                "The Math",
                "What does the cost math look like for restaurants?",
            ),
            (
                '"name": "Related Reading"',
                '"name": "How much does AI restaurant photography cost compared to a photographer?"',
            ),
            (
                '"text": "Want a complete I create done-for-you content built for your restaurant?"',
                '"text": "AI restaurant photography is far cheaper for ongoing social content and atmosphere imagery than repeated professional shoots. The best setup is usually hybrid: use AI for recurring content volume and real photographers for exact dishes, interiors, and hero assets."',
            ),
            (
                "<p><strong>Want a complete I create done-for-you content built for your restaurant?</strong></p>",
                "<p><strong>Want a complete AI restaurant photography system built for your restaurant?</strong></p>",
            ),
        ],
    },
    "social-media-content-strategy-small-business.html": {
        "replacements": [
            (
                '<p class="article-subtitle">Most small businesses post randomly and wonder why social media doesn\'t work. The fix isn\'t more content — it\'s a system. Here\'s the complete playbook for building one that actually drives results.</p>',
                '<p class="article-subtitle">A small business social media strategy works when it narrows to one primary platform, a few repeatable content pillars, and a batching system the business can actually maintain. This guide lays out the full operating system.</p>',
            ),
            (
                "Step 1: Pick Your Platform (Singular)",
                "How should a small business choose one primary platform?",
            ),
            (
                "Step 2: Define Your Content Pillars",
                "How do you define the right content pillars?",
            ),
            (
                "Step 3: The Content Mix Formula",
                "What content mix formula works for small businesses?",
            ),
            (
                "Step 4: Posting Frequency — The Honest Answer",
                "How often should a small business post?",
            ),
            (
                "Step 5: The Batching Workflow",
                "How do you batch content efficiently?",
            ),
            (
                "Step 6: Tools That Actually Matter",
                "What tools actually matter?",
            ),
            (
                "Step 7: Content Formats That Work in 2026",
                "What content formats work in 2026?",
            ),
            (
                "Step 8: Measuring What Actually Matters",
                "What metrics actually matter?",
            ),
            (
                "Step 9: Common Mistakes That Kill Small Business Social Media",
                "What mistakes kill small business social media results?",
            ),
            (
                "The System in One Page",
                "What does the system look like on one page?",
            ),
        ],
    },
}


def main():
    updated = []
    missing = []
    for filename, config in TOP_PAGES.items():
        path = BLOG_DIR / filename
        text = path.read_text(encoding="utf-8")
        original = text

        text = text.replace("https://loopworker.com/", "https://www.loopworker.com/")

        for old, new in config.get("replacements", []):
            if old not in text:
                missing.append((filename, old[:80]))
                continue
            text = text.replace(old, new)

        related = config.get("related")
        if related and "Related Reading" not in text:
            marker = '    <div class="cta-section">'
            if marker in text:
                text = text.replace(marker, related + "\n\n" + marker, 1)
            else:
                missing.append((filename, "cta marker for related block"))

        if text != original:
            path.write_text(text, encoding="utf-8")
            updated.append(filename)

    print(f"Updated {len(updated)} files:")
    for name in updated:
        print(f"  - {name}")

    if missing:
        print("\nMissing patterns:")
        for name, snippet in missing:
            print(f"  - {name}: {snippet!r}")


if __name__ == "__main__":
    main()
